### ISSUE TITLE
Ratings dont load anymore!

### ISSUE THREAD

**Issue by sevenalarm** [meooow25/carrot#62] opened 2024-08-13 17:10 UTC
It's been a while that it's had on and offs but now it's not working at all.
I've seen blogs in codeforces.com where they're saying the same thing...
Carrot is such a useful tool to satisfy our dread to know about how much we're gonna gain or lose, it's vital. Please fix it!

**Comment by meooow25** [comment] 2024-08-13 17:17
Hi, could you be more specific about what's not working?

I'm aware of some issues caused by the Codeforces API blocking access now and then. There is a possible workaround I want to try (#61) when I can.

However, right now I see Carrot working as expected.

![Screenshot 2024-08-13 at 22-46-16 Standings - Codeforces Round 966 (Div  3) - Codeforces](https://github.com/user-attachments/assets/34f28a90-1bfd-4ec3-92b4-5da1f6756a91)

**Comment by meooow25** [comment] 2024-08-18 01:52
Closing since there doesn't seem to be a problem. Please reopen if you have more information.

**Closed by meooow25** 2024-08-18 01:52 UTC
